/*****************************************************************************
* Model: blinky.qm
* File:  ./blinky.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/1) .................................................................*/
#include "qpn_port.h"
#include "bsp.h"
#include "project.h"

/*Q_DEFINE_THIS_FILE*/

/* Blinky class declaration ------------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct BlinkyTag {
/* protected: */
    QActive super;
} Blinky;

/* protected: */
static QState Blinky_initial(Blinky * const me);
static QState Blinky_off(Blinky * const me);
static QState Blinky_on(Blinky * const me);


/* Global objects ----------------------------------------------------------*/
Blinky AO_Blinky;        /* the single instance of the Blinky active object */

/* Blinky class definition -------------------------------------------------*/
/* @(/1/2) .................................................................*/
void Blinky_ctor(void) {
    QActive_ctor(&AO_Blinky.super, Q_STATE_CAST(&Blinky_initial));
}
/* @(/1/0) .................................................................*/
/* @(/1/0/0) ...............................................................*/
/* @(/1/0/0/0) */
static QState Blinky_initial(Blinky * const me) {
    return Q_TRAN(&Blinky_off);
}
/* @(/1/0/0/1) .............................................................*/
static QState Blinky_off(Blinky * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/0/0/1) */
        case Q_ENTRY_SIG: {
            QActive_arm((QActive *)me, BSP_TICKS_PER_SEC/2); /* 1/2 sec */
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/0/1/0) */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/0/0/2) .............................................................*/
static QState Blinky_on(Blinky * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/0/0/2) */
        case Q_ENTRY_SIG: {
            QActive_arm((QActive *)me, BSP_TICKS_PER_SEC/2); /* 1/2 sec */
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/0/2/0) */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

